source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"

# GitHub Pages compatible
group :jekyll_plugins do
  gem "github-pages", "~> 228"
end
